"""Pydantic I/O schemas for every worker and critic agent in the AutoTube AI pipeline."""
from agents.schemas.audio_render import (
    AssemblyOutput,
    VideoAssemblyInput,
    VoiceoverInput,
    VoiceoverOutput,
    VoiceoverSegment,
)
from agents.schemas.common import (
    ContentFormat,
    ContentType,
    CriticVerdict,
    PipelineStage,
    RunStatus,
    StageCost,
)
from agents.schemas.feedback import (
    LearningUpdate,
    NotificationEvent,
    NotificationSeverity,
    PerformanceSnapshot,
    PerformanceWindow,
)
from agents.schemas.publish import (
    ApprovalDecision,
    ApprovalPacket,
    ComplianceCheckInput,
    ComplianceCheckResult,
    MetadataInput,
    MetadataOutput,
    ThumbnailInput,
    ThumbnailOutput,
    UploadInput,
    UploadResult,
    UploadStatus,
    Visibility,
)
from agents.schemas.research import (
    StrategyDecision,
    StrategyInput,
    TopicCandidate,
    TrendResearchInput,
    TrendResearchOutput,
)
from agents.schemas.script import (
    ClaimVerification,
    FactCheckOutput,
    ScriptOutput,
    ScriptQAResult,
    ScriptWriterInput,
)
from agents.schemas.visual import (
    AssetOutput,
    AssetSourcingInput,
    SourcedAsset,
    VisualPlanningInput,
    VisualPlanOutput,
)

__all__ = [
    "ApprovalDecision",
    "ApprovalPacket",
    "AssemblyOutput",
    "AssetOutput",
    "AssetSourcingInput",
    "ClaimVerification",
    "ComplianceCheckInput",
    "ComplianceCheckResult",
    "ContentFormat",
    "ContentType",
    "CriticVerdict",
    "FactCheckOutput",
    "LearningUpdate",
    "MetadataInput",
    "MetadataOutput",
    "NotificationEvent",
    "NotificationSeverity",
    "PerformanceSnapshot",
    "PerformanceWindow",
    "PipelineStage",
    "RunStatus",
    "ScriptOutput",
    "ScriptQAResult",
    "ScriptWriterInput",
    "SourcedAsset",
    "StageCost",
    "StrategyDecision",
    "StrategyInput",
    "ThumbnailInput",
    "ThumbnailOutput",
    "TopicCandidate",
    "TrendResearchInput",
    "TrendResearchOutput",
    "UploadInput",
    "UploadResult",
    "UploadStatus",
    "VideoAssemblyInput",
    "Visibility",
    "VisualPlanOutput",
    "VisualPlanningInput",
    "VoiceoverInput",
    "VoiceoverOutput",
    "VoiceoverSegment",
]
